# Generated by Django 5.0.1 on 2024-02-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0002_alter_user_options_remove_user_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
    ]
