# Generated by Django 5.0.1 on 2024-02-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0003_remove_vehicle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
