# Generated by Django 5.0.1 on 2024-02-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0005_vehicle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
    ]
