# Generated by Django 5.0.1 on 2024-02-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vehicle", "0007_user_is_admin_user_is_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_user",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_user",
            field=models.BooleanField(default=False),
        ),
    ]
