# Generated by Django 5.0.1 on 2024-02-17 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0009_remove_userprofile_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Space_to_reserve',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.parkinglot'),
        ),
    ]
