# Generated by Django 5.0.1 on 2024-02-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Vehicle", "0010_contact_alter_vehicle_space_to_reserve_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="Feedback",
        ),
    ]
