# Generated by Django 5.0.1 on 2024-02-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vehicle", "0011_rename_contact_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglot",
            name="total_reserved_spaces",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
