# Generated by Django 5.0.1 on 2024-02-23 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0013_dailydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='DailyData',
        ),
    ]
