# Generated by Django 5.0.1 on 2024-02-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vehicle", "0017_paymentreceipt_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prebook",
            name="exit_time",
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="exit_time",
            field=models.DateTimeField(),
        ),
    ]
