# Generated by Django 5.0.1 on 2024-03-02 10:47

import Vehicle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0018_alter_prebook_exit_time_alter_vehicle_exit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='exit_time',
            field=models.DateTimeField(default=Vehicle.models.default_exit_time),
        ),
    ]
