# Generated by Django 5.0.6 on 2024-06-08 09:57

import Vehicle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vehicle", "0019_alter_vehicle_exit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prebook",
            name="exit_time",
            field=models.DateTimeField(default=Vehicle.models.default_exit_time),
        ),
    ]
